# ~/.bash_profile: executed by bash for login shells.

umask 002

# Load the dotfiles
for FILE in alias functions prompt 
do
	[ -f ~/.$FILE ] && source ~/.$FILE;
done
unset FILE

# remove duplicates in PATH : when we re-run this script, it wont add ~/bin again
PATH=~/bin:$PATH
PATH=`printf %s "$PATH" | awk -v RS=: '{ if (!arr[$0]++) {printf("%s%s",!ln++?"":":",$0)}}'`
export PATH=$PATH

export EDITOR=~/bin/nano
export HISTCONTROL=ignoredups:erasedups

